Repository PPSKSY-Cluster/backend, pull requests merged in 2022-06, with the labels that each got.

#13 Login/Logout, model validation
  README.md
  auth/auth.go
  db/mongodb.go
  db/usersDBInterface.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  handlers/users.go
  router.go
Labels: enhancement

#21 fix authentication
  auth/auth.go
  router.go
Labels: bug

#14 incorporate peter-evans/swagger-github-pages
  .github/workflows/pages_auto_update.yml
Labels: documentation, devops

#17 Testing
  .gitignore
  README.md
  api/c_resources.go
  api/router.go
  api/users.go
  db/c_resourceDBInterface.go
  db/testInterface.go
  go.mod
  go.sum
  main.go
  tests/c_resources_test.go
  tests/test.go
  tests/users_test.go
Labels: devops

#30 Docker
  Dockerfile
  README.md
  docker-compose.yml
Labels: devops

#34 Add build and test workflows
  .github/workflows/build_docker_compose.yml
  .github/workflows/test_api.yml
Labels: devops

#45 Reservations
  api/reservations.go
  api/router.go
  db/reservationDBInterface.go
  tests/reservations_test.go
Labels: enhancement

#43 Move pages/ to `gh-pages`
  .github/workflows/pages_auto_update.yml
  pages/dist/favicon-16x16.png
  pages/dist/favicon-32x32.png
  pages/dist/index.css
  pages/dist/oauth2-redirect.html
  pages/dist/swagger-initializer.js
  pages/dist/swagger-ui-bundle.js
  pages/dist/swagger-ui-bundle.js.map
  pages/dist/swagger-ui-es-bundle-core.js
  pages/dist/swagger-ui-es-bundle-core.js.map
  pages/dist/swagger-ui-es-bundle.js
  pages/dist/swagger-ui-es-bundle.js.map
  pages/dist/swagger-ui-standalone-preset.js
  pages/dist/swagger-ui-standalone-preset.js.map
  pages/dist/swagger-ui.css
  pages/dist/swagger-ui.css.map
  pages/dist/swagger-ui.js
  pages/dist/swagger-ui.js.map
  pages/index.html
  pages/spec.js
  pages/swagger-ui.version
Labels: documentation, enhancement
